# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: sjzclxy
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
mituh:
  jwt:
    #加密秘钥
    secret: f9bi38h8g3nbxfei
    # token有效时长
    expire: 604800
    header: Authorization
server:
  port: 8081
